// this file was generated by serverless-auto-swagger
module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "tutorial-demo",
    "version": "1"
  },
  "schemes": [
    "https"
  ],
  "paths": {
    "/tutorials": {
      "POST": {
        "summary": "createTutorial",
        "description": "",
        "operationId": "createTutorial",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "GET": {
        "summary": "listTutorials",
        "description": "",
        "operationId": "listTutorials",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/tutorials/{tutorialId}": {
      "GET": {
        "summary": "getTutorial",
        "description": "",
        "operationId": "getTutorial",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "tutorialId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "PUT": {
        "summary": "editTutorial",
        "description": "",
        "operationId": "editTutorial",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "tutorialId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      },
      "DELETE": {
        "summary": "deleteTutorial",
        "description": "",
        "operationId": "deleteTutorial",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "tutorialId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  }
};